# Generated by Django 4.2.13 on 2024-05-29 12:07

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', validators=[main.validators.validate_file_size])),
            ],
        ),
    ]
