# Generated by Django 4.2.13 on 2024-06-01 13:23

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='avatars/', validators=[main.validators.validate_file_size]),
        ),
    ]
