# Generated by Django 4.2.13 on 2024-06-14 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp1', models.DateTimeField(auto_now=True)),
                ('timestamp2', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp3', models.DateTimeField(auto_now=True, null=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_user2', to=settings.AUTH_USER_MODEL)),
                ('user3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_user3', to=settings.AUTH_USER_MODEL)),
                ('user4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_user4', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
