# Generated by Django 4.2.13 on 2024-06-14 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_tournament_timestamp1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='timestamp1',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='timestamp2',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='timestamp3',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='user3',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='user4',
        ),
        migrations.AddField(
            model_name='matchmaking',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tournament'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='size',
            field=models.IntegerField(default=4),
        ),
        migrations.CreateModel(
            name='TournamentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
