# Generated by Django 4.2.13 on 2024-06-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tournament_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
