# Generated by Django 4.2.13 on 2024-06-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_customuser_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_first',
            field=models.BooleanField(default=True),
        ),
    ]
