# Generated by Django 4.2.13 on 2024-06-20 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_customuser_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_first',
        ),
        migrations.AddField(
            model_name='matchmaking',
            name='parent_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='matchmaking',
            name='user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchmaking_user1', to=settings.AUTH_USER_MODEL),
        ),
    ]
