# Generated by Django 4.2.13 on 2024-06-19 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_customuser_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_first',
        ),
    ]
