# Generated by Django 4.2.13 on 2024-06-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_matchmaking_parent_id_matchmaking_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='count',
            new_name='num_users',
        ),
        migrations.AddField(
            model_name='matchmaking',
            name='level',
            field=models.IntegerField(default=-1),
        ),
    ]
