# Generated by Django 4.2.14 on 2024-07-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_count_tournament_num_users_matchmaking_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted')], default='P', max_length=1),
        ),
    ]
