# Generated by Django 4.2.14 on 2024-08-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_customuser_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(default='ja', max_length=10),
        ),
    ]
