# Generated by Django 4.2.14 on 2024-08-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_customuser_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='language',
        ),
    ]
