# Generated by Django 4.2.14 on 2024-08-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_matchmaking_ball_speed_matchmaking_is_3d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmaking',
            name='ai',
            field=models.IntegerField(default=2),
        ),
    ]
