# Generated by Django 4.2.14 on 2024-08-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_matchmaking_is_single'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='ball_speed',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_3d',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='match_point',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='paddle_size',
            field=models.IntegerField(default=2),
        ),
    ]
