# Generated by Django 4.2.14 on 2024-08-11 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_tournament_ball_speed_tournament_is_3d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmaking',
            name='point1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchmaking',
            name='point2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchmaking',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
