# Generated by Django 4.2.15 on 2024-08-13 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_doubles_matchmaking_user3_matchmaking_user4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doubles',
            name='is_complete',
        ),
    ]
