#!/usr/bin/python3

print("Content-type: text/html\n")
print("<html lang=\"ja\">")
print("<meta charset=\"UTF-8\">")
print("<title>tyonezawのページ</title>")
print("<body>")
print("<h1>tyonezawのinception</h1>")
print("<p>staticなページをpythonで作りました</p>")
print("<p>ちゃんとしたページを作るなら、ココらへんにhtmlをどんどん追加行けばいいのだけれど、別にコンテンツもないしこれでいいでしょ？</p>")
print("<p>一応レジュメっぽいものを書くとすれば、現在は42の学生です。</p>")
print("<p>42でC,C++をベースに様々な課題に取り組み中。</p>")
print("<p>セキュリティとか興味あります。ゲームとかアプリとか作ります。</p>")
print("</body>")
print("</html>")
